sources:
  - NimbleSurvey/Sources
templates:
  - tools/sourcery/templates
output:
  NimbleSurveyTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - NimbleSurvey
  autoMockableImports:
